export enum OrderStatus {
  PENDING = 'PENDING',
  PAID = 'PAID',
  PROCESSING = 'PROCESSING',
  SHIPPED = 'SHIPPED',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
  REFUNDED = 'REFUNDED',
}

export enum OrderSource {
  SURVEY = 'SURVEY',
  CATALOG = 'CATALOG',
  TREATMENT = 'TREATMENT',
}

export enum OrderDiscountType {
  COMBO = 'COMBO',
}

export enum CommerceSettingKey {
  SURVEY_COMBO_DISCOUNT_PCT = 'SURVEY_COMBO_DISCOUNT_PCT',
  SURVEY_COMBO_MIN_SUBTOTAL_VND = 'SURVEY_COMBO_MIN_SUBTOTAL_VND',
  TREATMENT_COMBO_DISCOUNT_PCT = 'TREATMENT_COMBO_DISCOUNT_PCT',
  TREATMENT_COMBO_MIN_SUBTOTAL_VND = 'TREATMENT_COMBO_MIN_SUBTOTAL_VND',
  LOW_STOCK_THRESHOLD = 'LOW_STOCK_THRESHOLD',
  BOOKING_CONFIRM_TIMEOUT_MIN = 'BOOKING_CONFIRM_TIMEOUT_MIN',
  BOOKING_NO_SHOW_GRACE_MIN = 'BOOKING_NO_SHOW_GRACE_MIN',
  BOOKING_MIN_LEAD_TIME_MIN = 'BOOKING_MIN_LEAD_TIME_MIN',
}

export enum TransactionStatus {
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  REFUNDED = 'REFUNDED',
}

export enum TransactionType {
  PRODUCT_PURCHASE = 'PRODUCT_PURCHASE',
  CONSULTATION_PAYMENT = 'CONSULTATION_PAYMENT',
  TREATMENT_PLAN_PAYMENT = 'TREATMENT_PLAN_PAYMENT',
  WALLET_TOPUP = 'WALLET_TOPUP',
  REFUND = 'REFUND',
  WITHDRAWAL = 'WITHDRAWAL',
  WITHDRAWAL_REVERSAL = 'WITHDRAWAL_REVERSAL',
  ESCROW_RELEASE = 'ESCROW_RELEASE',
  COMMISSION = 'COMMISSION',
}

/** Double-entry style accounts for platform ledger rows. */
export enum LedgerAccount {
  CUSTOMER_WALLET = 'CUSTOMER_WALLET',
  PLATFORM_ESCROW = 'PLATFORM_ESCROW',
  PLATFORM_REVENUE = 'PLATFORM_REVENUE',
  CLINIC_WALLET = 'CLINIC_WALLET',
  EXTERNAL_GATEWAY = 'EXTERNAL_GATEWAY',
  BANK_OUT = 'BANK_OUT',
}

export enum OrderCancellationStatus {
  REQUESTED = 'REQUESTED',
  REFUNDING = 'REFUNDING',
  REFUNDED = 'REFUNDED',
  AWAITING_RETURN = 'AWAITING_RETURN',
  RESTOCKED = 'RESTOCKED',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}

export enum OrderCancellationActor {
  CUSTOMER = 'CUSTOMER',
  STAFF = 'STAFF',
  SYSTEM = 'SYSTEM',
}
