export enum OrderStatus {
  PENDING = 'PENDING',
  PAID = 'PAID',
  PROCESSING = 'PROCESSING',
  SHIPPED = 'SHIPPED',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
  REFUNDED = 'REFUNDED',
}

export enum OrderSource {
  SURVEY = 'SURVEY',
  CATALOG = 'CATALOG',
}

export enum OrderDiscountType {
  COMBO = 'COMBO',
}

export enum CommerceSettingKey {
  SURVEY_COMBO_DISCOUNT_PCT = 'SURVEY_COMBO_DISCOUNT_PCT',
}

export enum TransactionStatus {
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  REFUNDED = 'REFUNDED',
}

export enum TransactionType {
  PRODUCT_PURCHASE = 'PRODUCT_PURCHASE',
  CONSULTATION_PAYMENT = 'CONSULTATION_PAYMENT',
  TREATMENT_PLAN_PAYMENT = 'TREATMENT_PLAN_PAYMENT',
  WALLET_TOPUP = 'WALLET_TOPUP',
  REFUND = 'REFUND',
  WITHDRAWAL = 'WITHDRAWAL',
  ESCROW_RELEASE = 'ESCROW_RELEASE',
  COMMISSION = 'COMMISSION',
}
