export enum ExpertSpecialty {
  DERMATOLOGY = 'DERMATOLOGY',
  COSMETIC_DERMATOLOGY = 'COSMETIC_DERMATOLOGY',
  ACNE_TREATMENT = 'ACNE_TREATMENT',
  ANTI_AGING = 'ANTI_AGING',
  PIGMENTATION = 'PIGMENTATION',
  LASER_THERAPY = 'LASER_THERAPY',
  AESTHETIC_MEDICINE = 'AESTHETIC_MEDICINE',
}
