export enum CommerceAnalyticsEventType {
  PRODUCT_VIEWED = 'PRODUCT_VIEWED',
  ADDED_TO_CART = 'ADDED_TO_CART',
  CHECKOUT_STARTED = 'CHECKOUT_STARTED',
  PURCHASE_COMPLETED = 'PURCHASE_COMPLETED',
}

export enum ClientCommerceAnalyticsEventType {
  PRODUCT_VIEWED = 'PRODUCT_VIEWED',
  ADDED_TO_CART = 'ADDED_TO_CART',
  CHECKOUT_STARTED = 'CHECKOUT_STARTED',
}
