export enum TreatmentStatus {
  DRAFT = 'DRAFT',
  ACTIVE = 'ACTIVE',
  PAUSED = 'PAUSED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum TreatmentPhaseType {
  INITIAL_ASSESSMENT = 'INITIAL_ASSESSMENT',
  ACTIVE_TREATMENT = 'ACTIVE_TREATMENT',
  MAINTENANCE = 'MAINTENANCE',
  RECOVERY = 'RECOVERY',
}

export enum TreatmentPhaseStatus {
  PENDING = 'PENDING',
  ACTIVE = 'ACTIVE',
  COMPLETED = 'COMPLETED',
}

export enum TreatmentEventType {
  CONSULTATION = 'CONSULTATION',
  PROGRESS_PHOTO = 'PROGRESS_PHOTO',
  MEDICATION_CHANGE = 'MEDICATION_CHANGE',
  INGREDIENT_OVERRIDE = 'INGREDIENT_OVERRIDE',
  MILESTONE = 'MILESTONE',
  FOLLOW_UP = 'FOLLOW_UP',
}

export enum TreatmentAccessStatus {
  ACTIVE = 'ACTIVE',
  EXPIRED = 'EXPIRED',
  REVOKED = 'REVOKED',
}
